
univ=("UNIVERSITAS KOMPUTER INDONESIA")
alamat=("Jl. Dipati Ukur 112-114, Bandung")
garis1=("---------------------------------------------------")
nama=("Oemar Bakri")
nim=("10205088")
jurusan=("Teknik Komputer")
fakultas=("Teknik dan Ilmu Komputer")
garis2=("---------------------------------------------------")

print(univ.center(50))
print(alamat.center(50))
print(garis1.center(50))
print("\tNama         : " +nama)
print("\tNIM          : " +nim)
print("\tJurusan      : " +jurusan)
print("\tFakultas     : " +fakultas) 
print(garis2.center(50))
print("Nama : Sedri sella Jumeni")